SELECT D.*,A.[NGAY_INSERT] ,
CASE  WHEN A.[NGAY_INSERT] IS NULL THEN 'Red' ELSE 'Green' END AS MCOLOR
FROM DM_SV D
LEFT JOIN 
(
	SELECT B.*,SV.[NGAY_INSERT]
	FROM
	(
		SELECT MAX(C.[ID]) AS ID,C.[COMPUTER_NAME], C.SERVICES_NAME,C.APP_TYPE 
		FROM SV C
		GROUP BY C.[COMPUTER_NAME], C.SERVICES_NAME,C.APP_TYPE
	) B
	INNER JOIN SV ON B.[ID]=SV.[ID]
	WHERE (DATEPART(HOUR,GETDATE())- DATEPART(HOUR,SV.NGAY_INSERT) < 1 )
) A
ON D.[COMPUTER_NAME]=A.[COMPUTER_NAME] AND D.[APP_TYPE]=A.[APP_TYPE] AND D.[SERVICES_NAME]=A.[SERVICES_NAME]