USE [TTDL]
GO

/****** Object:  Table [dbo].[SV]    Script Date: 10/13/2014 11:22:23 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SV](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[COMPUTER_NAME] [nvarchar](100) NOT NULL,
	[SERVICES_NAME] [nvarchar](250) NOT NULL,
	[APP_TYPE] [int] NOT NULL,
	[NGAY_INSERT] [datetime] NOT NULL,
	[TRANG_THAI] [int] NULL,
 CONSTRAINT [PK_SV] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO





USE [TTDL]
GO

/****** Object:  Table [dbo].[DM_SV]    Script Date: 10/13/2014 11:22:07 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DM_SV](
	[COMPUTER_NAME] [nvarchar](100) NOT NULL,
	[APP_TYPE] [int] NOT NULL,
	[SERVICES_NAME] [nvarchar](250) NOT NULL,
	[APP_NAME] [nvarchar](250) NOT NULL,
	[SERVICES_TYPE] [nvarchar](250) NOT NULL,
 CONSTRAINT [PK_DM_SV_1] PRIMARY KEY CLUSTERED 
(
	[SERVICES_NAME] ASC,
	[APP_TYPE] ASC,
	[COMPUTER_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


