//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace t.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("t.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///N501A_SIKNO AS SIKNO ,
        ///N501A_SGARI2 AS SGARI2 ,
        ///N501A_NOUKC2 AS NOUKC2 ,
        ///N501A_NOUKN2 AS NOUKN2 ,
        ///N501A_NOZEI2 AS NOZEI2 ,
        ///N501A_NOMEN2 AS NOMEN2 ,
        ///N501A_NOGEN2 AS NOGEN2 ,
        ///N501A_NOGAK2 AS NOGAK2 ,
        ///N501A_ZEUKS2 AS ZEUKS2 ,
        ///N501A_ZEZEI2 AS ZEZEI2 ,
        ///N501A_ZEMEN2 AS ZEMEN2 ,
        ///N501A_ZEGEN2 AS ZEGEN2 ,
        ///N501A_ZEGAK2 AS ZEGAK2 ,
        ///N501A_ZEDEF2 AS ZEDEF2 ,
        ///N501A_NOZET2 AS NOZET2 ,
        ///N501A_NOMET2 AS NOMET2 ,
        ///N501A_NOGTN2 AS NOGTN2 ,
        ///N501A_ZEGAT2 AS ZEGAT2 ,
        ///N501A_ZEDET2 AS ZEDET2 ,
        ///N501A_TITLE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MVIEW1_TOKHAIMD {
            get {
                return ResourceManager.GetString("MVIEW1_TOKHAIMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abc.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
