//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace t.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("t.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MVIEW1_TOKHAIMD {
            get {
                return ResourceManager.GetString("MVIEW1_TOKHAIMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///N501A_SIKNO AS SIKNO ,
        ///N501A_SINKD AS SINKD,
        ///N501A_SINKS AS SINKS,
        ///N501A_SHIKS AS SHIKS,
        ///N501A_YUNYC AS YUNYC,
        ///N501A_SINKS AS SINKS ,
        ///N501A_ENDAY2 AS ENDAY2,
        ///N501A_YUSYK AS YUSYK,
        ///N501A_YUNN2 AS YUNN2
        /// FROM N501A N1 WHERE {0}
        /// UNION 
        ///SELECT 
        ///N502A_SIKNO AS SIKNO ,
        ///N502A_SINKD AS SINKD,
        ///N502A_SINKS AS SINKS,
        ///N502A_SHIKS AS SHIKS,
        ///N502A_YUNYC AS YUNYC,
        ///N502A_SINKS AS SINKS ,
        ///N502A_ENDAY2 AS ENDAY2,
        ///N502A_YUSYK AS YUSYK,
        ///N502A_YUNN2 AS YUNN2
        /// FROM N502A N2 WHERE {0}.
        /// </summary>
        internal static string MVIEW1_TOKHAIMD2 {
            get {
                return ResourceManager.GetString("MVIEW1_TOKHAIMD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abc.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
