//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace t.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("t.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        /// {0}
        ///FROM N501A N1 
        ///WHERE {1}
        ///UNION 
        ///SELECT 
        ///  {2}
        ///FROM N502A N2 
        ///WHERE {3};
        ///
        ///SELECT 
        ///H.SIKNO,
        ///H.RANNB ,
        ///HINME,HINMC,
        ///ORGLC,
        ///TANI1,
        ///SURY1,
        ///TANKA,
        ///KAZTK,
        ///BPRIC,
        ///KANKG,
        ///KAZEI,
        ///KANRT,
        ///NAIBC_1,
        ///NAIRT_1,
        ///NAIGK_1,
        ///NAIBC_2,
        ///NAIRT_2,
        ///NAIGK_2,
        ///NAIBC_3,
        ///NAIRT_3,
        ///NAIGK_3,
        ///NAIBC_4,
        ///NAIRT_4,
        ///NAIGK_4,
        ///NAIBC_5,
        ///NAIRT_5,
        ///NAIGK_5,
        ///ORGNK,
        ///ATCD 
        ///
        ///FROM 
        ///(
        ///  SELECT 
        ///  N1.N501A_SIKNO AS SIKNO  
        ///  FROM N501A N1 WHERE {0}
        ///  UNION 
        ///  SELECT 
        ///  N2.N502A_SIKNO AS SIKNO 
        ///  FROM  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MVIEW1_TOKHAIMD2 {
            get {
                return ResourceManager.GetString("MVIEW1_TOKHAIMD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N1.N501A_SINKD AS SINKD ,
        ///N1.N501A_SINKS AS SINKS ,
        ///N1.N501A_SHIKS AS SHIKS ,
        ///N1.N501A_YUNYC AS YUNYC ,
        ///N1.N501A_YUSYK AS YUSYK ,
        ///N1.N501A_YUNN2 AS YUNN2 ,
        ///N1.N501A_CYUK1 AS CYUK1 ,
        ///N1.N501A_TRANS AS TRANS ,
        ///N1.N501A_TYBNA AS TYBNA ,
        ///N1.N501A_TYNEP AS TYNEP ,
        ///N1.N501A_AWBNB_1 AS AWBNB ,
        ///N1.N501A_AWBNB_2 AS AWBNB_2 ,
        ///N1.N501A_AWBNB_3 AS AWBNB_3 ,
        ///N1.N501A_AWBNB_4 AS AWBNB_4 ,
        ///N1.N501A_AWBNB_5 AS AWBNB_5 ,
        ///N1.N501A_TRORC AS TRORC ,
        ///N1.N501A_TRORN AS TRORN ,
        ///N1.N501A_TMDSI AS TMDSI ,
        ///N1.N501A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string N501A_FIELDS {
            get {
                return ResourceManager.GetString("N501A_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N2.N501A_SINKD AS SINKD ,
        ///N2.N501A_SINKS AS SINKS ,
        ///N2.N501A_SHIKS AS SHIKS ,
        ///N2.N501A_YUNYC AS YUNYC ,
        ///N2.N501A_YUSYK AS YUSYK ,
        ///N2.N501A_YUNN2 AS YUNN2 ,
        ///N2.N501A_CYUK1 AS CYUK1 ,
        ///N2.N501A_TRANS AS TRANS ,
        ///N2.N501A_TYBNA AS TYBNA ,
        ///N2.N501A_TYNEP AS TYNEP ,
        ///N2.N501A_AWBNB AS AWBNB ,
        ///NULL AS AWBNB_2 ,
        ///NULL AS AWBNB_3 ,
        ///NULL AS AWBNB_4 ,
        ///NULL AS AWBNB_5 ,
        ///N2.N501A_TRORC AS TRORC ,
        ///N2.N501A_TRORN AS TRORN ,
        ///N2.N501A_TMDSI AS TMDSI ,
        ///N2.N501A_TMDSM AS TMDSM ,
        ///N2.N501A_YSYOS_1 AS YSYOS_1 ,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string N502A_FIELDS {
            get {
                return ResourceManager.GetString("N502A_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abc.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
