USE [TRACUUTKWEB]
GO

/****** Object:  Table [dbo].[SDONVI]    Script Date: 10/21/2014 9:09:12 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SDONVI](
	[MA_DONVI] [nvarchar](15) NOT NULL,
	[TEN_DONVI] [nvarchar](500) NOT NULL,
 CONSTRAINT [PK_SDONVI] PRIMARY KEY CLUSTERED 
(
	[MA_DONVI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


