USE [TRACUUTKWEB]
GO

/****** Object:  Table [dbo].[SREPORT]    Script Date: 10/21/2014 9:09:22 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SREPORT](
	[RP_ID] [int] NOT NULL,
	[RP_USERNAME] [nvarchar](255) NOT NULL,
	[RP_CREATEDATE] [datetime] NULL,
	[RP_DISPLAY] [nvarchar](255) NULL,
	[RP_QUERY] [nvarchar](max) NULL,
	[RP_QUERY_MD5] [nvarchar](255) NULL,
	[RP_STATUS] [nvarchar](255) NULL,
	[RP_EXPORTDATE] [datetime] NULL,
	[RP_FILEPATH] [nvarchar](1000) NULL,
	[RP_FILENAME] [nvarchar](255) NULL,
 CONSTRAINT [PK_SREPORT] PRIMARY KEY CLUSTERED 
(
	[RP_ID] ASC,
	[RP_USERNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


