USE [TRACUUTKWEB]
GO

/****** Object:  Table [dbo].[SUSER]    Script Date: 10/21/2014 9:09:36 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SUSER](
	[ST_USERNAME] [nvarchar](255) NOT NULL,
	[ST_PASSWORD] [nvarchar](255) NULL,
 CONSTRAINT [PK_SUSER] PRIMARY KEY CLUSTERED 
(
	[ST_USERNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


